Repository pasabanov/locale-match, pull requests merged in 2024-09, with the labels that each got.

#3 README.md: added crates.io and metrics badges
  README.md
Labels: essential

#4 Deleted redundant run configurations
  .idea/runConfigurations/Debug.xml
  .idea/runConfigurations/Release.xml
Labels: configuration

#5 Updated crates.io badge and added docs.rs badge
  README.md
Labels: essential

#6 Added two more test cases for best_matching_locale
  src/posix.rs
Labels: tests

#7 Added GitHub release badge, fixed badge colors
  README.md
Labels: essential

#8 Changed library description
  Cargo.toml
  README.md
  src/bcp47.rs
  src/lib.rs
  src/posix.rs
Labels: documentation, essential

#9 README.md: Fixed badges alternative text
  README.md
Labels: essential

#10 Changed best_matching_locale signature
  README.md
  src/bcp47.rs
  src/posix.rs
Labels: enhancement, performance, refactor, user-experience

#11 Changed LGPL notices from doc to regular comments; small doc improvements
  src/bcp47.rs
  src/lib.rs
  src/posix.rs
Labels: documentation, essential

#12 Added more extensive documentation to `lib.rs`
  src/lib.rs
Labels: documentation
